### ISSUE TITLE
1.19.2 Server crash

### ISSUE THREAD

**Issue by ModernGamingWorld** [JDKDigital/lootbundles#2]
[crash-2024-05-02_08.58.09-server.txt](https://github.com/JDKDigital/lootbundles/files/15190767/crash-2024-05-02_08.58.09-server.txt)

Not sure whos mods is the cause of the crash, but it blames this mod and Easy Mob Farm

**Comment by JaisDK** [comment]
the crash is from this mod

did you change the loot modifier or are you playing a pack that has it changed?

**Comment by ModernGamingWorld** [comment]
@JaisDK Yes, I have a certain way I dont want people bypassing things in my modpack with Lootbundle and mob farms, so I removed some of the easy vanilla mobs/animals

**Comment by JaisDK** [comment]
What did you change them to?

**Comment by ModernGamingWorld** [comment]
@JaisDK I removed them from the file to stop them from being included. otherwise there was no way to stop them

**Comment by JaisDK** [comment]
can I see the changes? and how did you apply the changes? with a datapack?

**Comment by ModernGamingWorld** [comment]
its all posted under here in my Datapack mod 
https://github.com/AzureDoom/Modern-s-Monumental-Recipe/tree/1.19.2/src/main/resources/data/lootbundles/loot_modifiers

all I did was copy over your loot modifers and remove what i did not want to drop, it has been working fine till the server crashed

**Comment by JaisDK** [comment]
you set maxCount to 0, that's what's causing the crash

**Comment by ModernGamingWorld** [comment]
@JaisDK is there any easy way to disable stuff like Loot fragments and whatnot? As I do not use them, its kind of dumb in my eyes to have them cause server crashes if a modpack developer wants them disabled. I only use the loot bundles for Quests and do not need its recipes. I had players complain to me that loot fragments drop, but are useless if they are not attached to anything like recipes. There should be a feature or configuration option to disable things like loot bundles or fragment dropping if we only want them in our quest books. if there is no easy way to solve this, I might have to find a different mod to use

**Comment by JaisDK** [comment]
yes, use the same files as you have but set the probability to 0 not the maxcount
